# Generated by Django 5.2 on 2025-04-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motocicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('linea', models.CharField(max_length=100)),
                ('modelo', models.IntegerField()),
                ('placa', models.CharField(max_length=100)),
                ('chasis', models.CharField(max_length=100)),
                ('motor', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
